version: "2.1"

executors:
  # `main` uses the `cimg/go:1.15` docker image.
  main:
    docker:
      - image: cimg/go:1.15

jobs:

  # `test_go` tests the gocat source code.
  test_go:
    executor: main
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: false
      - run: make fmt
      - run: make imports
      - run: make test_go
      - run: git diff --exit-code

workflows:
  version: 2
  main:
    jobs:
      - test_go
